{{/*
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vso.resourceNameWithTruncation" (dict "root" . "name" "proxy-role") }}
  labels:
    app.kubernetes.io/component: controller-manager
  {{- include "vso.chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vso.resourceNameWithTruncation" (dict "root" . "name" "proxy-rolebinding") }}
  labels:
    app.kubernetes.io/component: controller-manager
  {{- include "vso.chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vso.resourceNameWithTruncation" (dict "root" . "name" "proxy-role") }}
subjects:
- kind: ServiceAccount
  name: {{ include "vso.resourceNameWithTruncation" (dict "root" . "name" "controller-manager") }}
  namespace: {{ .Release.Namespace }}
