apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: vault-secrets-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: VaultAuth is the Schema for the vaultauths API
      displayName: Vault Auth
      kind: VaultAuth
      name: vaultauths.secrets.hashicorp.com
      version: v1alpha1
    - description: VaultConnection is the Schema for the vaultconnections API
      displayName: Vault Connection
      kind: VaultConnection
      name: vaultconnections.secrets.hashicorp.com
      version: v1alpha1
    - description: VaultDynamicSecret is the Schema for the vaultdynamicsecrets API
      displayName: Vault Dynamic Secret
      kind: VaultDynamicSecret
      name: vaultdynamicsecrets.secrets.hashicorp.com
      version: v1alpha1
    - description: VaultPKISecret is the Schema for the vaultpkisecrets API
      displayName: Vault PKISecret
      kind: VaultPKISecret
      name: vaultpkisecrets.secrets.hashicorp.com
      version: v1alpha1
    - description: VaultStaticSecret is the Schema for the vaultstaticsecrets API
      displayName: Vault Static Secret
      kind: VaultStaticSecret
      name: vaultstaticsecrets.secrets.hashicorp.com
      version: v1alpha1
    - description: VaultAuth is the Schema for the vaultauths API
      displayName: Vault Auth
      kind: VaultAuth
      name: vaultauths.secrets.hashicorp.com
      version: v1beta1
    - description: VaultConnection is the Schema for the vaultconnections API
      displayName: Vault Connection
      kind: VaultConnection
      name: vaultconnections.secrets.hashicorp.com
      version: v1beta1
    - description: VaultDynamicSecret is the Schema for the vaultdynamicsecrets API
      displayName: Vault Dynamic Secret
      kind: VaultDynamicSecret
      name: vaultdynamicsecrets.secrets.hashicorp.com
      version: v1beta1
    - description: VaultPKISecret is the Schema for the vaultpkisecrets API
      displayName: Vault PKISecret
      kind: VaultPKISecret
      name: vaultpkisecrets.secrets.hashicorp.com
      version: v1beta1
    - description: VaultStaticSecret is the Schema for the vaultstaticsecrets API
      displayName: Vault Static Secret
      kind: VaultStaticSecret
      name: vaultstaticsecrets.secrets.hashicorp.com
      version: v1beta1
  description: that's some operator
  displayName: Vault Secrets Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAYAAABccqhmAAAACXBIWXMAABYlAAAWJQFJUiTwAAAKnUlEQVR4nO3dTW4bRxrG8dfG7J0bRHMDr7kZB+DezgmsG1gHIDBa8ADKCaKcIPaegJUNt/ENRrpBdAIN2umKHEUkq7vr432q/j/Au0BWSD9/FT/EfvHw8GAA+vSS+x3oFwEAOkYAgI4RAKBjBADoGAEAOlY1ALvV5rvhD/8AgTqKvA9gt9q8MbPw58zMvj/wn96Z2a2Z3Qx/1vvtDf8ugHyyBWC32rw2swsze2dmr2Z+mXsz+2hm18QASC95AMaf9pdm9p/E3+1vw9clBEA6yQKwW22Go/2Vmb3NfP8QAiCRJAHYrTbDMf96wVF/DkIALLQ4ALvVZvip/6HiHUEIgJkWBWC32gw/9d87ufEJATDR7AA4G/+3CAEQaVYAHBz7YxAC4ITJAditNudm9rPQDUsIgAMmBWB8qe9L4Wf7UyEEwBNTfxfgSnT8Nr4x6fNutbkZ36wEdC/6BDCO5nNDNxgnAnRvygngsrEbixMBuhd1Amjwp/9zOBGgO7EngPMObhhOBOhO7AngD+En/+biRIDmnQxAJ8f/YwgBmhXzEKD34zAPDdAsAhCPEKA5MQ8Benz8H4OHBpAXEwCuHnocIYAsrguwHA8NIOvoCWD85Z//cfdOwokAMjgBpMeJADJ4DiA/TgRwixNAfpwI4FZMAO64+5IgBHAnJgC33G1JEQK4ERMAHrvmQQhQHQGojxCgGn4d2B9eNUAxsa8CfOQuKYYTAYqJPQEM1/r/nbulCk4EyGbKpwLfZLjmP+IRAiTX86cCq+GhAZKbemWg4bmAt9wNLnAiwGI9XRqsVYQAs825OOg7M/uVm9wdQoDJWr48eK8IAaLNCoD9GYFrM3vPTe0WIcBJswNgREAFIcBBiwJgPBxQQgjwD4sDYI9PDF7z6oAEQoC/JAmAPb5EeMX7BGQQAqQLQDC+S+2Stw3LIAQdSx6AgBDIIQQdyhaAgBDIIQQdyR6AgBDIIQQdKBaAgBDIIQQNKx6AgBDIIQQNqhaAgBDIIQQNqR6AgBDIIQQNcBOAgBDIIQTC3AUgIARyCIEgtwEICIEcQiDEfQACQiCHEAiQCUBACOQQAsfkAhAQAjmEwCHZAASEQA4hcEQ+AAEhkEMIHGgmAAEhkEMIKmouAAEhkEMIKmg2AAEhkEMICmo+AAEhkEMICugmAAEhkEMIMuouAAEhkEMIMug2AAEhkEMIEuo+AAEhkEMIEiAATxACOYRgAQJwACGQQwhmIAAnEAI5hGACAhCJEMghBBEIwESEQA4hOIIAzEQI5BCCZxCAhQiBHELwDQKQCCGQ030IjACkRwjkdB0CApAJIZDTZQgIQGaEQE5XISAAhRACOV2EgAAURgjkNB0CAlAJIZDTZAgIQGWEQE5TISAAThACOU2EgAA4QwjkSIeAADhFCORIhoAAOEcI5EiFgACIIARyJEJAAMQQAjmuQ0AARBECOS5DQADEEQI5rkJAABpBCOS4CAEBaAwhkFM1BASgUYRATpUQEIDGEQI5RUNAADpBCOQUCQEB6AwhkJM1BASgU4RATpYQEIDOEQI5n8zsYr3f3qb4xgkAviIEUu7N7Hy9335c+k0TAPwNIZDy03q/vVjyDRMAPIsQyPhlvd+ez/1mCQCOIgQSZkeAACAKIXBv1sMBAoBJCIFrP059YpAAYBZC4NLw6sDrKS8Rvuzr9kEqwxtS1vvtEIEfxjepoL5XZnY15bvgBIAkOBG48kPsOwY5ASAJTgSuXMZ+M5wAkAUnguqiTgGcAJAFJ4Lqot4XwAkARXAiKO5+vd9+d+ovJQAoihAUdfJhAA8BUBQPDYp6c+ovIwCoghAUQQDgGyHI6uzUF+c5ALjCcwRprffbF8e+ICcAuMKJoCxOAHCNE8Fi/z72y0GcAICOcQKAS/zkT+PUcwD/Evp/QQcYflkEAC4w/CzuTn1RAoCqGH5WJz8ZiACgCoZfxMlfByYAKIrhF3UyALwKgCIYfnFRvw7MCQBZMfxqoj4enAAgC4ZfXdSnAxMAJMXwXfhtvd9+iflGCACSYPiuRH8qMAHAIgzfnU+x1wQwAoC5GL5Lw6XBJl0glABgEobv2vmU6wIaAUAshu/eT1OvDGy8EQinMHwJv6z326gLgTzFCQDPYvgyZo/fCACeYvhShmP/pCf9niIA+IrhS7kfn/Cb/Jj/KQLQOYYv59PwUt/UZ/sPIQCdYvhyho9Iv5zyJp8YBKAzDF9OluEHBKATDF9O1uEHBKBxDF9OkeEHBKBRDF9O0eEHBKAxDF9OleEHBKARDF9O1eEHBEAcw5fjYvgBARDF8OW4Gn5AAMQwfDkuhx8QABEMX47r4QcEwDmGL0di+AEBcIrhy5EafkAAnGH4ciSHHxAAJxi+HOnhBwSgMoYvp4nhBwSgEoYvp6nhBwSgMIYvp8nhBwSgEIYvp+nhBwQgM4Yvp4vhBwQgE4Yvp6vhBwQgMYYvp8vhBwQgEYYvp+vhBwRgIYYvh+F/gwDMxPDlMPxnEICJGL4chn8EAYjE8OUw/AgE4ASGL4fhT0AADmD4chj+DATgCYYvh+EvQABGDF8Ow0+g+wAwfDkMP6FuA8Dw5TD8DLoLAMOXw/Az6iYADF8Owy+g+QAwfDkMv6BmA8Dw5TD8CpoLAMOXw/AraiYADF8Ow3dAPgAMXw7Dd0Q2AAxfDsN3SC4ADF8Ow3dMJgAMXw7DF+A+AAxfDsMX4jYADF8OwxfkLgAMXw7DF+YmAAxfDsNvQPUAMHw5DL8h1QLA8OUw/AYVDwDDl8PwG1YsAAxfDsPvQPYAMHw5DL8j2QLA8OUw/A4lDwDDl8PwO5YsALvV5szMrszsbe83qgiGjzQB2K025+P4X3GTusfw8ZfFAditNsPwP3CTusfw8Q+LArBbba7N7D03q2sMHwfNDgDjd4/h46RZARiP/YzfJ4aPaC8eHh4m3VrjE34/cxO7w/Ax2aQAjC/1feHZflcYPmab+hCAl/r8YPhYLPoEML7D7zM3eXUMH8lMOQFccrNXxfCRXNQJYLfavDaz37n5q2D4yCb2BHDBXVAcw0d2sQF4x11RDMNHMScDMD75xzP/+TF8FBdzAnjD3ZIVw0c1BKAeho/qYgJwxt2UFMOHGzEB+J67KwmGD3dkLg8ujOHDraMBGH/5B/MwfLjHCSA9hg8ZJ98KvFttpn1gQL8YPuRwAliO4UNWTADueCXgWQwf8mICcEsA/obhoxkxAbjhMl9fMXw0JzYA/+34rmf4aFbsB4L80eFvBDJ8NC/2VYCPHV0HgOGjG7EB6OEqQAwf3ZnyqcCtPhnI8NGtqZ8K3NLHgjN8dG/qlYGG5wLeit9oDB8YTX0r8MX4CUGKrwgwfOCJORcHHT4h+FehG5LhAwdMDoA9Xh78g/MbleEDJ8wKgP0ZAa8vDTJ8INLsAJi/CDB8YKJFATAfDwcYPjDT4gDY4xOD14VfHWD4wEJJAmCPHyB6VeB9AgwfSCRZAILxWoKXGd42zPCBxJIHINitNq/HNw69W/DQ4H78TcSr9X77Jf13CfQtWwC+NZ4Kwp+zIx8xdjd+BNnwU/6Gn/ZAXkUCcEi48Mh6v73lfgbKqxoAAHW95PYH+kUAgI4RAKBjBADoGAEAOkYAgF6Z2f8B/iC4szHaiNYAAAAASUVORK5CYII=
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - secrets
  - vault
  - something
  - else
  links:
  - name: Vault Secrets Operator
    url: https://vault-secrets-operator.domain
  maintainers:
  - email: user@example.com
    name: user
  maturity: alpha
  provider:
    name: HashiCorp
  version: 0.0.0
