# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/vault-secrets-operator.clusterserviceversion.yaml
- ../default
- ../samples
- ../scorecard
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
